---
name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addr
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Get git metadata
        id: docker
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: sculch/addr

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sculch/addr:latest

      - name: Update DockerHub metadata
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sculch/addr
          short-description: "golang server for libpostal data"
